java_binary(
    name = "totaldiff",
    srcs = glob(["src/main/java/com/mss/**/*.java"]),
    main_class = "com.mss.totaldiff.Main",
    deps = [
        "@maven//:com_fasterxml_jackson_core_jackson_core",
    ],
)
